import Head from 'next/head';
import { NextPage } from 'next';
import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion'; 

interface Playlist {
  title: string,
  creator: string,
  votes: number,
  playlistId?: string,
};

const Home: NextPage<{ playlists: Playlist[] }> = ({ playlists }) => {
  const [featuredPlaylistId, setFeaturedPlaylistId] = useState('6EhWsKdmBEFPuO6QYzoFS3');

  const handleClick = (playlist: Playlist) => {
    playlist.playlistId && setFeaturedPlaylistId(playlist.playlistId);
  };

  const iframeVariants = {
    hidden: { opacity: 0, y: 15 },
    visible: { opacity: 1, y: 0 },
  };

  const iframeTransition = {
    duration: 0.3,
    ease: 'easeInOut',
  };

  return (
    <>
      <Head>
        <title>the playlist game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-7xl mx-auto p-6'>
        <div className='mb-12'>
          <h1 className='text-3xl mb-6 font-semibold'>
            <span>welcome to </span><u>the playlist game</u>
          </h1>
          <h2 className='text-2xl mb-2'><i>to participate in today's game:</i></h2>
          <ol>
            <li>1. create a <strong>public</strong> Spotify playlist that you feel matches today's vibe (5 tracks minimum).</li>
            <li>2. copy your Spotify playlist link and paste it below: </li>
            <input className='bg-white border border-gray-400 rounded-sm mr-2'></input>
            <button className='border border-gray-400 rounded-sm px-1'>submit</button>
            <li>3. browse & vote for your favorites! </li>
          </ol>
        </div>
        <hr />
        <div className='text-3xl mx-auto my-12'>
          <span>today's vibe: </span>
          <span className='text-red-400 text-6xl'><strong>LUDICROUSLY CAPACIOUS</strong></span>
        </div>
        <div className='flex flex-wrap'>
          <table className={`w-full md:w-1/2 pr-6 max-h-full overflow-y-auto`}>
            {playlists.map((playlist, _) => (
              <tr key={playlist.title} className={`border border-red-400 h-24 ${playlist?.playlistId === featuredPlaylistId && 'bg-gray-200'}`} onClick={() => handleClick(playlist)}>
                <td className='py-3 px-3'>{playlist.title}</td>
                <td>{playlist.creator}</td>
                <td>{playlist.votes}</td>
              </tr>
            ))}
          </table>
          <div className='relative w-full md:w-1/2 h-full px-6'>
            <AnimatePresence>
              <motion.div className='absolute inset-0 w-full pl-6'
                  key={featuredPlaylistId}
                  initial="hidden"
                  animate="visible"
                  exit="hidden"
                  variants={iframeVariants}
                  transition={iframeTransition}
              >
                <iframe 
                        src={`https://open.spotify.com/embed/playlist/${featuredPlaylistId}`}
                        width="100%"
                        height="550px"
                        allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
                        loading="lazy"
                />
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps(){
  const playlists: Playlist[] = [
    {
      'title': 'playlist 1',
      'creator': 'user1',
      'votes': 5,
      'playlistId': '4yrjcrcigdxcWVJHSrNaVc',
    },
    {
      'title': 'playlist 2',
      'creator': 'user2',
      'votes': 2,
      'playlistId': '6EhWsKdmBEFPuO6QYzoFS3',
    },
    {
      'title': 'playlist 3',
      'creator': 'user1',
      'votes': 0
    },
    {
      'title': 'playlist 3',
      'creator': 'user1',
      'votes': 3
    },
    {
      'title': 'playlist 4',
      'creator': 'user4',
      'votes': 3
    },
    {
      'title': 'playlist 4',
      'creator': 'user4',
      'votes': 3
    },
    {
      'title': 'playlist 4',
      'creator': 'user4',
      'votes': 3
    },
    {
      'title': 'playlist 4',
      'creator': 'user4',
      'votes': 3
    },
    {
      'title': 'playlist 4',
      'creator': 'user4',
      'votes': 3
    },
  ];

  return {
    props: {
      playlists,
    },
    revalidate: 20,
  }
}

export default Home;